# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d15b2f73-b5f6-4241-abcd-d4c02fb894d9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d15b2f73-b5f6-4241-abcd-d4c02fb894d9".device = "/dev/disk/by-uuid/d15b2f73-b5f6-4241-abcd-d4c02fb894d9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A9C-01BC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-141bf220-dbc6-4e2e-b022-4f917dfba929"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
